// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"wire/event"
	"wire/greeter"
	"wire/message"
)

// Injectors from wire.go:

func InitializeEvent() event.Event {
	messageMessage := message.NewMessage()
	greeterGreeter := greeter.NewGreeter(messageMessage)
	eventEvent := event.NewEvent(greeterGreeter)
	return eventEvent
}

func InitializeCustomEvent(phrase string) event.Event {
	messageMessage := message.NewCustomMessage(phrase)
	greeterGreeter := greeter.NewGreeter(messageMessage)
	eventEvent := event.NewEvent(greeterGreeter)
	return eventEvent
}
