###
GET http://127.0.0.1:8080/user
Accept: application/json

###
GET http://127.0.0.1:8080/user/rui
Accept: application/json

### normal request passes
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "name": "rui",
  "age": 18,
  "email": "test@test.com"
}

### bad request
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "name": "rui",
  "email": "test@test.com"
}
